#!/usr/bin/env bash
set -euo pipefail

HOSTNAME="arch"
TIMEZONE="Europe/Paris"
LOCALE="en_US.UTF-8"
KEYMAP="dvorak"
XKBLAYOUT="us"
XKBVARIANT="dvorak-alt-intl"

BASE_PACKAGES="base linux linux-firmware"
ESSENTIAL_PACKAGES="base-devel networkmanager power-profiles-daemon bluez dnsutils alsa-utils mlocate vim sudo git btop iwd zsh tree ncdu neovim lynx nmap rsync traceroute zip yadm plymouth go"
ADDITIONAL_PACKAGES="man-db man-pages texinfo btrfs-progs"
MICROCODE_PACKAGE=$(grep -q GenuineIntel /proc/cpuinfo && echo intel-ucode || echo amd-ucode)
GUI_PACKAGES="gnome-shell gdm gnome-control-center gnome-shell-extensions gnome-tweaks gnome-keyring gnome-backgrounds gnome-system-monitor kitty docker firefox"

USER="th"
PASSWORD=test
IS_TEST=false

usage() {
    cat <<EOF
Usage:
    $0 --efi <EFI PARTITION> --root <ROOT PARTITION> [options]

Options:
    Additional boot partition (if existing efi too small)
    --xbootldr <XBOOTLDR PARTITION>
}
EOF
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --efi)
                EFI_PARTITION="$2"
                shift 2
                ;;
            --xbootldr)
                XBOOTLDR_PARTITION="$2"
                shift 2
                ;;
            --root)
                ROOT_PARTITION="$2"
                shift 2
                ;;
            --test)
                IS_TEST=true
                shift 1
                ;;
            -h)
                usage
                exit 0
                ;;
            *)
                echo "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done
    [[ -v EFI_PARTITION && -v ROOT_PARTITION ]] || {
        echo "Missing required option" >&2
        usage
        exit 1
    }
}

confirm() {
    echo "Configuration Summary:"
    echo "===================================="
    echo "EFI partition:        $EFI_PARTITION"
    echo "ROOT partition:       $ROOT_PARTITION"
    echo "XBOOTLDR partition:   ${XBOOTLDR_PARTITION:-(not set)}"
    echo "===================================="
    [[ $IS_TEST == true ]] || {
        read -p "Continue with these settings? (y/n): " -n 1 -r; echo
        [[ $REPLY =~ ^[Yy]$ ]] || {
            echo "Aborted" >&2
            exit 1
        }
    }
}

get_password() {
    local -n var=$1
    local password password_confirm
    while true; do
        read -rs -p "$2 :" password; echo
        read -rs -p "Confirm password :" password_confirm; echo
        [ "${password}" == "${password_confirm}" ] && break
        echo "Passwords do not match! Try again." >&2
    done
    var="${password}"
}

prepare_disk() {
    [[ $IS_TEST == true ]] || get_password PASSWORD "Password"

    EFI_MOUNTPOINT="boot"
    if [[ -v XBOOTLDR_PARTITION ]]; then
        echo "==> Formatting XBOOTLDR partition..."
        mkfs.fat -F32 "$XBOOTLDR_PARTITION"
        EFI_MOUNTPOINT="efi"
        fi

    echo "==> Setting up LUKS encryption on root partition..."
    echo -n "$PASSWORD" | cryptsetup luksFormat "$ROOT_PARTITION" -q

    echo "==> Opening encrypted partition..."
    echo -n "$PASSWORD" | cryptsetup open "$ROOT_PARTITION" cryptroot

    echo "==> Formatting root partition..."
    mkfs.btrfs  /dev/mapper/cryptroot

    echo "==> Mounting filesystems..."
    mount /dev/mapper/cryptroot /mnt

    mkdir -p /mnt/$EFI_MOUNTPOINT
    mount "$EFI_PARTITION" "/mnt/$EFI_MOUNTPOINT"

    if [[ -v XBOOTLDR_PARTITION ]]; then
        mkdir -p /mnt/boot
        mount "$XBOOTLDR_PARTITION" /mnt/boot
    fi
}

install_base_system() {
    echo "==> Installing base system..."
    pacstrap /mnt $BASE_PACKAGES $ESSENTIAL_PACKAGES $ADDITIONAL_PACKAGES $MICROCODE_PACKAGE $GUI_PACKAGES

    echo "==> Generating fstab..."
    genfstab -U /mnt >> /mnt/etc/fstab

    echo "==> Configure swapfile..."
    btrfs subvolume create /mnt/swap
    btrfs filesystem mkswapfile --size $(awk '/MemTotal/ {print $2}' /proc/meminfo)k --uuid clear /mnt/swap/swapfile
    echo '/swap/swapfile none swap defaults 0 0' >> /mnt/etc/fstab
}

configure_system() {

    echo "==> Configuring system..."
    ROOT_UUID=$(blkid -s UUID -o value "$ROOT_PARTITION")
    SWAP_OFFSET=$(btrfs inspect-internal map-swapfile -r /mnt/swap/swapfile)
    arch-chroot -S /mnt /bin/bash <<EOF
set -euo pipefail

# Set timezone
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
hwclock --systohc

# Set locale
echo "$LOCALE UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=$LOCALE" > /etc/locale.conf

# Set keymap
cat > /etc/vconsole.conf <<VCONSOLE
KEYMAP=$KEYMAP
XKBLAYOUT=$XKBLAYOUT
XKBVARIANT=$XKBVARIANT
VCONSOLE

# Set hostname
echo "$HOSTNAME" > /etc/hostname

# Configure mkinitcpio for encryption
sed -i 's/^HOOKS=.*/HOOKS=(base systemd plymouth autodetect modconf kms keyboard sd-vconsole block sd-encrypt filesystems fsck)/' /etc/mkinitcpio.conf

# Regenerate initramfs
mkinitcpio -P

# Install systemd-boot
if [[ -v XBOOTLDR_PARTITION ]]; then
    bootctl install --esp-path=/efi --boot-path=/boot
else
    bootctl install
fi

# Configure systemd-boot loader
cat > /$EFI_MOUNTPOINT/loader/loader.conf <<LOADER
default arch.conf
timeout 1
console-mode max
editor no
LOADER

# Create boot entry
cat > /boot/loader/entries/arch.conf <<BOOTENTRY
title   Arch Linux
linux   /vmlinuz-linux
initrd  /$MICROCODE_PACKAGE.img
initrd  /initramfs-linux.img
options rd.luks.name=$ROOT_UUID=cryptroot root=/dev/mapper/cryptroot resume=/dev/mapper/cryptroot resume_offset=$SWAP_OFFSET rw quiet splash
BOOTENTRY

# Create fallback boot entry
cat > /boot/loader/entries/arch-fallback.conf <<BOOTENTRY
title   Arch Linux (fallback initramfs)
linux   /vmlinuz-linux
initrd  /$MICROCODE_PACKAGE.img
initrd  /initramfs-linux-fallback.img
options rd.luks.name=$ROOT_UUID=cryptroot root=/dev/mapper/cryptroot rw
BOOTENTRY

# Create user if specified
useradd -m -G wheel -s /bin/bash $USER

# Set passwords
chpasswd <<SETPASSWORD
root:${PASSWORD}
$USER:${PASSWORD}
SETPASSWORD

# Enable sudo for wheel group
sed -i 's|^[[:space:]]*#[[:space:]]*\(%wheel ALL=(ALL:ALL) NOPASSWD: ALL\)|\1|' /etc/sudoers

# Enable networking
systemctl enable NetworkManager
systemctl enable bluetooth

# Gui Configuration
systemctl enable gdm
sed -i '/^\[daemon\]/a AutomaticLoginEnable=True\nAutomaticLogin=$USER' /etc/gdm/custom.conf

# Configure docker
systemctl enable docker
usermod -aG docker $USER

# Configure default shell: zsh
chsh -s /usr/bin/zsh
chsh -s /usr/bin/zsh $USER

sync
echo ""
echo "==> System configuration complete!"

EOF
}

post_install_user() {
    echo "==> Post Install"

    arch-chroot /mnt runuser -l $USER -c "
        pwd
        ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''
        git clone https://aur.archlinux.org/yay.git
        (cd yay && makepkg -si --noconfirm) && rm -rf yay
        yay -S --noconfirm ttf-hack zinit starship eza ccat bat
        yadm clone https://github.com/taebow/dotbytes.git
        source .zshrc
    "

    arch-chroot /mnt /bin/bash -c "
        sed -i \
            -e 's|^\(%wheel ALL=(ALL:ALL) NOPASSWD: ALL\)|# \1|' \
            -e 's|^[[:space:]]*#[[:space:]]*\(%wheel ALL=(ALL:ALL) ALL\)|\1|' \
            /etc/sudoers
    "
}

unmount_and_close() {
    umount /mnt/$EFI_MOUNTPOINT
    [[ -v XBOOTLDR_PARTITION ]] && umount /mnt/boot
    umount /mnt
    cryptsetup close cryptroot
}

main() {
    parse_args "$@"
    confirm
    prepare_disk
    install_base_system
    configure_system
    post_install_user
    unmount_and_close
}

main "$@"
